/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
#include <string.h>


void
calc_prog_1(char *host, char *op, int x,int y)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  add_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALC_PROG, CALC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	add_1_arg.a=x;
	add_1_arg.b=y;
	if (strcmp (op, "add") == 0) {
		result_1 = add_1(&add_1_arg, clnt);
	}
	else if (strcmp (op, "sub") == 0) {
		result_1 = sub_1(&add_1_arg, clnt);
	}
	else if (strcmp (op, "mul") == 0) {
		result_1 = mul_1(&add_1_arg, clnt);
	}
	else if (strcmp (op, "div") == 0) {
		result_1 = divide_1(&add_1_arg, clnt);
	}
	else {
		printf ("operacao invalida: %s\n", op);
		clnt_destroy (clnt);
		exit (1);
	}
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("Result:%d\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 5) {
		printf ("usage: %s server_host add|sub|mul|div a b\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calc_prog_1 (host, argv[2], atoi(argv[3]), atoi(argv[4]));

exit (0);
}
