/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

int *
add_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("add(%d, %d) a chamada dos argumentos a e b \n", argp->a, argp->b );
	result = argp->a + argp->b;

	return &result;
}

int *
sub_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("sub(%d, %d) a chamada dos argumentos a e b \n", argp->a, argp->b );
	result = argp->a - argp->b;

	return &result;
}

int *
mul_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("mul(%d, %d) a chamada dos argumentos a e b \n", argp->a, argp->b );
	result = argp->a * argp->b;

	return &result;
}

int *
divide_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("div(%d, %d) a chamada dos argumentos a e b \n", argp->a, argp->b );
	if (argp->b == 0) {
		printf("divisao por zero, retornando 0 \n");
		result = 0;
	}
	else {
		result = argp->a / argp->b;
	}

	return &result;
}
